name = "foodtruck"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# KV namespace for storing menu and schedule data
[[kv_namespaces]]
binding = "CONTENT"
id = "a1c14d5b12214f8387b677a0d77e4a19"
preview_id = "3fdc036dcc1c4707adbe5323d90b292a"
